spring.config.import=optional:file:.env[.properties]
spring.application.name=payflow
server.port=${PORT}
# Kafka
spring.kafka.bootstrap-servers=${KAFKA_SERVER}
spring.kafka.consumer.group-id=${CONSUMER_GROUP_ID}
spring.kafka.consumer.auto-offset-reset=earliest
logging.level.org.springframework.kafka=DEBUG
logging.level.org.apache.kafka.clients.consumer=INFO
# Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
# Security
security.jwt.secret=${JWT_SECRET}
security.jwt.expiration=${JWT_EXPIRATION}
# PostgresSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
# Logging
logging.level.org.hibernate=info
logging.level.org.flywaydb=DEBUG
# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
# Resend
resend.api-key=${RESEND_API_KEY}