spring.application.name=payflow
server.port=8080
# Security
security.jwt.secret=change-this-to-a-long-random-secret-key-for-payflow
security.jwt.expiration=3600000
# PostgresSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/payflow
spring.datasource.username=postgres
spring.datasource.password=Abdallah@123
# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
# Logging
logging.level.org.hibernate=info
logging.level.org.flywaydb=DEBUG
# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
